<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ResonitePath Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')">C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath>
        <ResonitePath Condition="Exists('D:\SteamLibrary\steamapps\common\Resonite\')">D:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
        <ResonitePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')">$(HOME)/.steam/steam/steamapps/common/Resonite/</ResonitePath>
        <ResonitePath Condition="Exists('/mnt/LocalDisk2/SteamLibrary/steamapps/common/Resonite/')">/mnt/LocalDisk2/SteamLibrary/steamapps/common/Resonite/</ResonitePath>
        <ResonitePath Condition="Exists('/mnt/LocalDisk2/SteamLibrary/steamapps/common/ResoniteWin/')">/mnt/LocalDisk2/SteamLibrary/steamapps/common/ResoniteWin/</ResonitePath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Elements.Assets">
            <HintPath>$(ResonitePath)\Elements.Assets.dll</HintPath>
        </Reference>

        <Reference Include="Elements.Assets">
            <HintPath>$(ResonitePath)\Elements.Data.dll</HintPath>
        </Reference>

        <Reference Include="Elements.Core">
            <HintPath>$(ResonitePath)\Elements.Core.dll</HintPath>
        </Reference>

        <Reference Include="FrooxEngine">
            <HintPath>$(ResonitePath)\FrooxEngine.dll</HintPath>
        </Reference>

        <Reference Include="ProtoFlux.Nodes.Core">
            <HintPath>$(ResonitePath)\ProtoFlux.Nodes.Core.dll</HintPath>
        </Reference>

        <Reference Include="ProtoFlux.Nodes.FrooxEngine">
            <HintPath>$(ResonitePath)\ProtoFlux.Nodes.FrooxEngine.dll</HintPath>
        </Reference>

        <Reference Include="ProtoFluxBindings">
            <HintPath>$(ResonitePath)\ProtoFluxBindings.dll</HintPath>
        </Reference>

        <Reference Include="Rug.Osc">
            <HintPath>$(ResonitePath)\Rug.Osc.dll</HintPath>
        </Reference>

        <Reference Include="SkyFrost.Base">
            <HintPath>$(ResonitePath)\SkyFrost.Base.dll</HintPath>
        </Reference>

        <Reference Include="SkyFrost.Base.Models">
            <HintPath>$(ResonitePath)\SkyFrost.Base.Models.dll</HintPath>
        </Reference>

        <Reference Include="PhotonDust">
            <HintPath>$(ResonitePath)\PhotonDust.dll</HintPath>
        </Reference>

        <Reference Include="System.Threading.Tasks.DataFlow">
            <HintPath>$(ResonitePath)\Renderer\Renderite.Renderer_Data\Managed\System.Threading.Tasks.Dataflow.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
